/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mine.views;

import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AQUAVIRUS
 */
public class FaultyFrame extends javax.swing.JFrame {

    private Vector<Vector<String>> data;
    private Vector<Vector<String>> faultyVector;
    private Vector<String> header;
    private DefaultTableModel tableModel;
    /**
     * Creates new form FaultyFrame
     */
    public FaultyFrame() {
        this.data = data;
        
        header = new Vector<>();
        header.add( "Block Number" );
        header.add( "Address" );
        header.add( "Block Nick" );
        //tableModel = new DefaultTableModel( data, header );
        
        initComponents();
        setDefaultCloseOperation( DISPOSE_ON_CLOSE );
    }
    
    /**
    public void updateTableData( Vector<Vector<String>> data, List<Integer> faultyBlockNumbers )
    {
        Iterator iterator = faultyBlockNumbers.iterator();
        while( iterator.hasNext() )
        {
            faultyVector.add( data.get( ( int )iterator.next() ) );
        }
        faultyTable.setModel( new DefaultTableModel( data, header ) );
        tableModel.fireTableDataChanged();
    }
    * */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
