/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mine.views;

import java.awt.event.ActionListener;
import javax.swing.Box;
import javax.swing.event.MenuListener;

/**
 *
 * @author AQUAVIRUS
 */
public class MenuView11 extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MenuView11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        homeMenu = new javax.swing.JMenu();
        createBlockMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        allBlocksMenuItem = new javax.swing.JMenuItem();
        runningMenuItem = new javax.swing.JMenuItem();
        editBlockMenu = new javax.swing.JMenu();
        allocateMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(fileMenu);

        homeMenu.setText("Home");
        homeMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        createBlockMenuItem.setText("Create New Block");
        homeMenu.add(createBlockMenuItem);

        jMenuBar1.add(homeMenu);

        viewMenu.setText("View");
        viewMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        allBlocksMenuItem.setText("All Blocks");
        allBlocksMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBlocksMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(allBlocksMenuItem);

        runningMenuItem.setText("Running");
        viewMenu.add(runningMenuItem);

        jMenuBar1.add(viewMenu);

        editBlockMenu.setText("Edit Block");
        editBlockMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(editBlockMenu);

        allocateMenu.setText("Allocate");
        allocateMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        allocateMenu.setIconTextGap(6);
        allocateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allocateMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(allocateMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allBlocksMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBlocksMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allBlocksMenuItemActionPerformed

    private void allocateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allocateMenuActionPerformed
        // TODO add your handling code here:
        System.out.println( 437846 );
    }//GEN-LAST:event_allocateMenuActionPerformed

    public void addHomeMenuActionListener( ActionListener listener )
    {
        homeMenu.addActionListener( listener );
    }
    
    public void addEditMenuActionListener( ActionListener listener )
    {
        editBlockMenu.addActionListener( listener );
    }
    
    public void addCreateBlockMenuItemActionListener( ActionListener listener )
    {
        createBlockMenuItem.addActionListener( listener );
    }
    
    public void addViewMenuActionListener( ActionListener listener )
    {
        viewMenu.addActionListener( listener );
    }
    
    public void addAllocateMenuListener( MenuListener listener )
    {
        allocateMenu.addMenuListener(listener );
    }
    
    public void addAllBlocksMenuItemActionListener( ActionListener listener )
    {
        allBlocksMenuItem.addActionListener( listener );
    }
    
    public void addEditBlockMenuActionListener( ActionListener listener )
    {
        editBlockMenu.addActionListener( listener );
    }
    
    public void addRunningBlocksMenuItemActionListener( ActionListener listener )
    {
        runningMenuItem.addActionListener( listener );
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem allBlocksMenuItem;
    private javax.swing.JMenu allocateMenu;
    private javax.swing.JMenuItem createBlockMenuItem;
    private javax.swing.JMenu editBlockMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem runningMenuItem;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
